=== Milka20013/WJB0DC_XMLGyak/WJB0DC_1011/BM_Kurzusfelvetel.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

    
   



    <xs:complexType name="hallgato" type="hallgatoTipus">
        <xs:sequence>
            <xs:element name="hnev" type="xs:string"/>
            <xs:element name="szulev" type="xs:string"/>
            <xs:element name="szak" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="kurzusok" type="kurzusokTipus">
        <xs:complexType>
            <xs:element name="kurzus">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="kurzusnev" type="xs:string"/>
                        <xs:element name="kredit" type="xs:string"/>
                        <xs:element name="hely" type="xs:string" />
                        <xs:element name="idopont" type="xs:string"/>
                        <xs:element name="oktato" type="xs:string"/>
                        <xs:element name="oraado" type="xs:string" minOccurs="0"/>
                    </xs:sequence>
                </xs:complexType>
                <xs:attribute name="id" type="idTipus"/>
                <xs:attribute name="jovahagyas" type="jovahagyasTipus" default="igen"/>
            </xs:element>
        </xs:complexType>
    </xs:complexType>

    <xs:simpleType name="tanevTipus">
        <xs:restriction base="xs:string">
            <xsd:pattern value="[0-9]{3}-[0-9]{2}-[0-9]{4}"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="jovahagyasTipus">
        <xs:restriction base="xs:string">
            <xs:enumeration value="igen"/>
            <xs:enumeration value="nem"/>
        </xs:restriction>
    </xs:simpleType>


    <xs:element name="WJB0DC_kurzusfelvetel">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="hallgato">
                </xs:element>
                <xs:element ref="kurzusok">
                </xs:element>
            </xs:sequence>
        </xs:complexType>
        <xs:attribute name="tanev" type="tanevTipus"/>
        <xs:attribute name="egyetem" type="xs:string"/>
    </xs:element>

</xs:schema>

=== Milka20013/WJB0DC_XMLGyak/WJB0DC_1011/BM_Kurzusfelvetel.xml
<?xml version="1.0" encoding="utf-8"?>
<WJB0DC_kurzusfelvetel xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="BM_Kurzusfelvetel.xsd" tanev="2023/2024" egyetem="ME">
    <hallgato>
        <hnev>Bordás Milán</hnev>
        <szulev>2002</szulev>
        <szak evf="3">Programtervező informatikus</szak>
    </hallgato>
    <kurzusok>
        <kurzus id="0" nyelv="magyar" jovahagyas="igen">
            <kurzusnev>XML</kurzusnev>
            <kredit>5</kredit>
            <hely>30</hely>
            <idopont>szerda 12-14</idopont>
            <oktato>Dr. Bednarik László</oktato>
        </kurzus>
        <kurzus id="1" nyelv="magyar">
            <kurzusnev>Mesterséges intelligencia</kurzusnev>
            <kredit>5</kredit>
            <hely>120</hely>
            <idopont>kedd 10-12</idopont>
            <oktato>Dr. Kunné Tamás Judit</oktato>
            <oraado>Fazekas Levente</oraado>
        </kurzus>
        <kurzus id="2" nyelv="magyar" jovahagyas="nem">
            <kurzusnev>Játék prototipusok</kurzusnev>
            <kredit>5</kredit>
            <hely>10</hely>
            <idopont>csütörtök 16-20</idopont>
            <oktato>Kiss Áron</oktato>
        </kurzus>
        <kurzus id="3" nyelv="magyar">
            <kurzusnev>Vállalati Információs Rendszerek</kurzusnev>
            <kredit>5</kredit>
            <hely>60</hely>
            <idopont>szerda 14-16</idopont>
            <oktato>Dr. Sasvári Péter</oktato>
          </kurzus>
    </kurzusok>
</WJB0DC_kurzusfelvetel>
