=== Milka20013/WJB0DC_XMLGyak/XMLTaskWJB0DC/XMLSchemaWJB0DC.xsd
<?xml version="1.0" encoding="utf-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

    <!-- Egyszerű típusok -->
    <xs:element name="nev" type="xs:string" />
    <xs:element name="alapito_tag" type="xs:string" />
    <xs:element name="eletkor" type="xs:integer" />
    <xs:element name="szuletesi_datum" type="DatumTipus" />
    <xs:element name="alapitas_datuma" type="DatumTipus" />
    <xs:element name="osszeg" type="xs:integer" />
    <xs:element name="orszag" type="xs:string" />
    <xs:element name="jatektipus" type="JatekTipusTipus" />
    <xs:element name="mettol" type="xs:integer" />
    <xs:element name="meddig" type="xs:integer" />
    <xs:element name="helyezes" type="HelyezesTipus" />
    <xs:element name="datum" type="DatumTipus" />
    <xs:element name="helyszin" type="xs:string" />

    <!-- Saját típusok -->
    <xs:simpleType name="DatumTipus">
        <xs:restriction base="xs:date">
            <xs:minInclusive value="1900-01-01" />
            <xs:maxInclusive value="2023-12-31" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="JatekTipusTipus">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Lövöldözős"></xs:enumeration>
            <xs:enumeration value="Több játékos"></xs:enumeration>
            <xs:enumeration value="Akció"></xs:enumeration>
            <xs:enumeration value="MOBA"></xs:enumeration>
            <xs:enumeration value="Stratégia"></xs:enumeration>
            <xs:enumeration value="Labdarúgás"></xs:enumeration>
            <xs:enumeration value="Ügyességi"></xs:enumeration>

        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="HelyezesTipus">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="1" />
            <xs:maxInclusive value="99"/>
        </xs:restriction>
    </xs:simpleType>


    <!-- Komplex típusok -->
    <xs:complexType name="SzponzorTipus">
        <xs:sequence>
            <xs:element ref="nev" />
            <xs:element ref="osszeg" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="CsapatTipus">
        <xs:sequence>
            <xs:element ref="alapitas_datuma"/>
            <xs:element name="Szponzor" type="SzponzorTipus" />
            <xs:element ref="alapito_tag" minOccurs="1" maxOccurs="10"/>
        </xs:sequence>
        <xs:attribute name="CSAzon" type="xs:string" />
    </xs:complexType>

    <xs:complexType name="JatekosTipus">
        <xs:sequence>
            <xs:element ref="nev" />
            <xs:element ref="orszag" />
            <xs:element ref="szuletesi_datum"/>
            <xs:element ref="eletkor"/>
        </xs:sequence>
        <xs:attribute name="PAzon" type="xs:integer" />
        <xs:attribute name="CSAzon" type="xs:string" />
        <xs:attribute name="JAzon" type="xs:integer" />
    </xs:complexType>

    <xs:complexType name="JatekTipus">
        <xs:sequence>
            <xs:element ref="nev" />
            <xs:element name="jatektipus" type="JatekTipusTipus" minOccurs="1" maxOccurs="10"/>
        </xs:sequence>
        <xs:attribute name="JAzon" type="xs:integer" />
    </xs:complexType>

    <xs:complexType name="VersenyszamTipus">
        <xs:attribute name="JAzon" type="xs:integer" />
        <xs:attribute name="VAzon" type="xs:integer" />
    </xs:complexType>

    <xs:complexType name="VezetoTipus">
        <xs:sequence>
            <xs:element ref="nev" />
            <xs:element ref="szuletesi_datum"/>
            <xs:element ref="mettol"/>
            <xs:element ref="meddig" minOccurs="0"/>
            <xs:element ref="eletkor"/>
        </xs:sequence>
        <xs:attribute name="LAzon" type="xs:integer" />
        <xs:attribute name="CSAzon" type="xs:string" />
    </xs:complexType>

    <xs:complexType name="VersenyezTipus">
        <xs:sequence>
            <xs:element ref="helyezes" />
        </xs:sequence>
        <xs:attribute name="CSAzon" type="xs:string" />
        <xs:attribute name="VAzon" type="xs:integer" />
    </xs:complexType>

    <xs:complexType name="VersenyTipus">
        <xs:sequence>
            <xs:element ref="nev" />
            <xs:element ref="datum" />
            <xs:element ref="helyszin" />
        </xs:sequence>
        <xs:attribute name="VAzon" type="xs:integer" />
    </xs:complexType>

    <!-- Elemek -->
    <xs:element name="WJB0DC_ESportok">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Csapat" type="CsapatTipus" maxOccurs="unbounded" />
                <xs:element name="Jatekos" type="JatekosTipus" maxOccurs="unbounded" />
                <xs:element name="Jatek" type="JatekTipus" maxOccurs="unbounded" />
                <xs:element name="Versenyszam" type="VersenyszamTipus" maxOccurs="unbounded" />
                <xs:element name="Vezeto" type="VezetoTipus" maxOccurs="unbounded" />
                <xs:element name="Versenyez" type="VersenyezTipus" maxOccurs="unbounded" />
                <xs:element name="Verseny" type="VersenyTipus" maxOccurs="unbounded" />
            </xs:sequence>
        </xs:complexType>

        <!--Elsődleges kulcsok-->

        <xs:key name="CsapatKulcs">
            <xs:selector xpath="Csapat" />
            <xs:field xpath="@CSAzon" />
        </xs:key>

        <xs:key name="JatekosKulcs">
            <xs:selector xpath="Jatekos" />
            <xs:field xpath="@PAzon" />
        </xs:key>

        <xs:key name="JatekKulcs">
            <xs:selector xpath="Jatek" />
            <xs:field xpath="@JAzon" />
        </xs:key>

        <xs:key name="VezetoKulcs">
            <xs:selector xpath="Vezeto" />
            <xs:field xpath="@LAzon" />
        </xs:key>

        <xs:key name="VersenyKulcs">
            <xs:selector xpath="Verseny" />
            <xs:field xpath="@VAzon" />
        </xs:key>

        <!-- Idegen kulcsok -->

        <xs:keyref name="JatekosCsapatKulcs" refer="CsapatKulcs">
            <xs:selector xpath="Jatekos" />
            <xs:field xpath="@CSAzon" />
        </xs:keyref>

        <xs:keyref name="JatekosJatekKulcs" refer="JatekKulcs">
            <xs:selector xpath="Jatekos" />
            <xs:field xpath="@JAzon" />
        </xs:keyref>

        <xs:keyref name="VersenyszamJatekKulcs" refer="JatekKulcs">
            <xs:selector xpath="Versenyszam" />
            <xs:field xpath="@JAzon" />
        </xs:keyref>

        <xs:keyref name="VersenyszamVersenyKulcs" refer="VersenyKulcs">
            <xs:selector xpath="Versenyszam" />
            <xs:field xpath="@VAzon" />
        </xs:keyref>

        <xs:keyref name="VezetoCsapatKulcs" refer="CsapatKulcs">
            <xs:selector xpath="Vezeto" />
            <xs:field xpath="@CSAzon" />
        </xs:keyref>

        <xs:keyref name="VersenyezCsapatKulcs" refer="CsapatKulcs">
            <xs:selector xpath="Versenyez" />
            <xs:field xpath="@CSAzon" />
        </xs:keyref>

        <xs:keyref name="VersenyezVersenyKulcs" refer="VersenyKulcs">
            <xs:selector xpath="Versenyez" />
            <xs:field xpath="@VAzon" />
        </xs:keyref>
    </xs:element>
</xs:schema>

=== Milka20013/WJB0DC_XMLGyak/XMLTaskWJB0DC/XMLWJB0DC.xml
<?xml version="1.0" encoding="utf-8"?>

<WJB0DC_ESportok xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="XMLSchemaWJB0DC.xsd" >

    <!-- Csapatok -->
    <Csapat CSAzon="Kerge Kecskék">
        <alapitas_datuma>2002-04-06</alapitas_datuma>
        <Szponzor>
            <nev>Nestlé</nev>
            <osszeg>50000</osszeg>
        </Szponzor>
        <alapito_tag>Kiss János</alapito_tag>
        <alapito_tag>Nagy Martin</alapito_tag>
    </Csapat>
    <Csapat CSAzon="Zöld Békák">
        <alapitas_datuma>2002-04-06</alapitas_datuma>
        <Szponzor>
            <nev>Nestlé</nev>
            <osszeg>75000</osszeg>
        </Szponzor>
        <alapito_tag>Magyar Márk</alapito_tag>
        <alapito_tag>Kossuth Máté</alapito_tag>
    </Csapat>
    <Csapat CSAzon="Kutyások">
        <alapitas_datuma>2002-05-01</alapitas_datuma>
        <Szponzor>
            <nev>FIFA</nev>
            <osszeg>100000</osszeg>
        </Szponzor>
        <alapito_tag>Nemes Géza</alapito_tag>
    </Csapat>

    <!--Játékosok-->
    <Jatekos PAzon="1" CSAzon="Kerge Kecskék" JAzon="1">
        <nev>Havas Henrik</nev>
        <orszag>Magyarország</orszag>
        <szuletesi_datum>1998-12-01</szuletesi_datum>
        <eletkor>24</eletkor>
    </Jatekos>
    <Jatekos PAzon="2" CSAzon="Kerge Kecskék" JAzon="1">
        <nev>Arany Anna</nev>
        <orszag>Magyarország</orszag>
        <szuletesi_datum>2003-11-18</szuletesi_datum>
        <eletkor>20</eletkor>
    </Jatekos>
    <Jatekos PAzon="3" CSAzon="Zöld Békák" JAzon="1">
        <nev>Kiss Anita</nev>
        <orszag>Magyarország</orszag>
        <szuletesi_datum>1999-10-11</szuletesi_datum>
        <eletkor>24</eletkor>
    </Jatekos>
    <Jatekos PAzon="4" CSAzon="Zöld Békák" JAzon="1">
        <nev>Nagy Hugó</nev>
        <orszag>Magyarország</orszag>
        <szuletesi_datum>1999-07-11</szuletesi_datum>
        <eletkor>24</eletkor>
    </Jatekos>
    <Jatekos PAzon="5" CSAzon="Kutyások" JAzon="2">
        <nev>Németh Ottó</nev>
        <orszag>Magyarország</orszag>
        <szuletesi_datum>2000-05-07</szuletesi_datum>
        <eletkor>23</eletkor>
    </Jatekos>
    <Jatekos PAzon="6" CSAzon="Kutyások" JAzon="2">
        <nev>Ding Liren</nev>
        <orszag>Kína</orszag>
        <szuletesi_datum>1995-12-01</szuletesi_datum>
        <eletkor>28</eletkor>
    </Jatekos>

    <!-- Játékok -->
    <Jatek JAzon="1">
        <nev>CS-GO</nev>
        <jatektipus>Lövöldözős</jatektipus>
        <jatektipus>Több játékos</jatektipus>
        <jatektipus>Akció</jatektipus>
    </Jatek>
    <Jatek JAzon="2">
        <nev>LoL</nev>
        <jatektipus>MOBA</jatektipus>
        <jatektipus>Több játékos</jatektipus>
        <jatektipus>Stratégia</jatektipus>
    </Jatek>
    <Jatek JAzon="3">
        <nev>FIFA</nev>
        <jatektipus>Labdarúgás</jatektipus>
        <jatektipus>Több játékos</jatektipus>
        <jatektipus>Ügyességi</jatektipus>
    </Jatek>

    <!-- Versenyszámok (kapcsoló tábla) -->
    <Versenyszam JAzon="1" VAzon="1"></Versenyszam>
    <Versenyszam JAzon="1" VAzon="2"></Versenyszam>
    <Versenyszam JAzon="2" VAzon="3"></Versenyszam>
    <Versenyszam JAzon="1" VAzon="3"></Versenyszam>
    <Versenyszam JAzon="2" VAzon="4"></Versenyszam>

    <!-- Vezetők -->
    <Vezeto LAzon="1" CSAzon="Kerge Kecskék">
        <nev>Alantas Balázs</nev>
        <szuletesi_datum>1975-04-01</szuletesi_datum>
        <mettol>2002</mettol>
        <meddig>2008</meddig>
        <eletkor>48</eletkor>
    </Vezeto>
    <Vezeto LAzon="2" CSAzon="Kerge Kecskék">
        <nev>Kovács Ágnes</nev>
        <szuletesi_datum>1982-09-21</szuletesi_datum>
        <mettol>2008</mettol>
        <eletkor>41</eletkor>
    </Vezeto>
    <Vezeto LAzon="3" CSAzon="Zöld Békák">
        <nev>Tóth Szilvia</nev>
        <szuletesi_datum>1979-12-24</szuletesi_datum>
        <mettol>2002</mettol>
        <eletkor>41</eletkor>
    </Vezeto>
    <Vezeto LAzon="4" CSAzon="Kutyások">
        <nev>Németh László</nev>
        <szuletesi_datum>1970-01-16</szuletesi_datum>
        <mettol>2002</mettol>
        <eletkor>53</eletkor>
    </Vezeto>

    <!-- Versenyez kapcsoló táblák -->
    <Versenyez CSAzon="Kerge Kecskék" VAzon="1">
        <helyezes>1</helyezes>
    </Versenyez>
    <Versenyez CSAzon="Zöld Békák" VAzon="1">
        <helyezes>2</helyezes>
    </Versenyez>
    <Versenyez CSAzon="Kutyások" VAzon="3">
        <helyezes>1</helyezes>
    </Versenyez>
    <Versenyez CSAzon="Kutyások" VAzon="4">
        <helyezes>1</helyezes>
    </Versenyez>

     <!-- Versenyek -->
     <Verseny VAzon="1">
        <nev>CS-GO Championship Las Vegas</nev>
        <datum>2010-10-04</datum>
        <helyszin>Las Vegas</helyszin>
     </Verseny>
     <Verseny VAzon="2">
        <nev>CS-GO Championship Dublin</nev>
        <datum>2012-10-04</datum>
        <helyszin>Dublin</helyszin>
     </Verseny>
     <Verseny VAzon="3">
        <nev>ESport Cup</nev>
        <datum>2014-05-04</datum>
        <helyszin>Berlin</helyszin>
     </Verseny>
     <Verseny VAzon="4">
        <nev>Play IT!</nev>
        <datum>2020-10-10</datum>
        <helyszin>Budapest</helyszin>
     </Verseny>
    

</WJB0DC_ESportok>
